### ISSUE TITLE
Char array inside struct does not terminate correctly

### ISSUE THREAD

**Issue by bakadave** [jwrw/ESP_EEPROM#18]
Problem: I've been trying to save a char array inside a struct (only the array for now but used a struct to support features later) and while it appeared to save correctly it did not retrieve the array correctly.

Soltion: If I add another variable to the struct everything works.

```
struct EEPROM_struct {
    char uid[36];
    uint8_t temp = 0x33;
}eepromVal;
```

**Comment by jwrw** [comment]
Sorry for the slow response but hopefully your workaround is working for you or you've added some extra features that has made the issue go away.  I've tried to replicate this but it seems to work OK for me so this is most probably due to some compiler 'feature' of the compiler you are using or some optimisation that has gone a little haywire? The following snippet seems to work as expected...
'''
#include <ESP_EEPROM.h>

struct EEPROM_struct1 {
    char uid[36];
} eepromVal, result;

void setup() {
  Serial.begin(9600);

  eepromVal.uid[35] = 99;

  EEPROM.begin(sizeof(eepromVal));
  EEPROM.put(0, eepromVal);
  EEPROM.commit();
  EEPROM.get(0, result);

  Serial.printf("uid[35] original = %d; retrieved = %d", eepromVal.uid[35], result.uid[35]);
}

void loop() {
}
'''

**Comment by bakadave** [comment]
Thank you for getting back to me. My workaround seems to work and I'd rather not fix something that's (mostly) not broken. If I use ESP_EEPROM in the future I'll see if it works on my end.
